require 'spec_helper'
require 'json'

# Unit tests for Phrase::AutomationEventsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'AutomationEventsApi' do
  before do
    # run before each test
    @api_instance = Phrase::AutomationEventsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AutomationEventsApi' do
    it 'should create an instance of AutomationEventsApi' do
      expect(@api_instance).to be_instance_of(Phrase::AutomationEventsApi)
    end
  end

  # unit tests for account_automation_events_list
  # List automation events for an account
  # Returns the run history across all automations in the account, newest-first.  Use &#x60;automation_id&#x60; to narrow results to a single automation. Use &#x60;project_id&#x60; or &#x60;project_ids&#x60; to narrow by project.  For feature availability, see [Jobs (Strings)](https://support.phrase.com/hc/en-us/articles/5784100517788-Jobs-Strings). 
  # @param account_id Account ID
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_phrase_app_otp Two-Factor-Authentication token (optional)
  # @option opts [Integer] :page Page number
  # @option opts [Integer] :per_page Limit on the number of objects to be returned, between 1 and 100. 25 by default
  # @option opts [String] :automation_id Filter events to a single automation by its ID.
  # @option opts [String] :state Filter events by outcome state. Unrecognized values are ignored.
  # @option opts [String] :triggered_by Filter events by what triggered the automation run. Unrecognized values are ignored.
  # @option opts [String] :project_id Filter events by project ID. Accepts a single ID or a comma-separated list of IDs.
  # @option opts [Array<String>] :project_ids Filter events by one or more project IDs.
  # @option opts [String] :created_after Return only events created after this ISO 8601 timestamp. Returns 400 if the value is not a valid date-time.
  # @option opts [String] :created_before Return only events created before this ISO 8601 timestamp. Returns 400 if the value is not a valid date-time.
  # @return [Array<AutomationEvent>]
  describe 'account_automation_events_list test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for automation_events_list
  # List events for an automation
  # Returns the run history for a specific automation, newest-first.  For feature availability, see [Jobs (Strings)](https://support.phrase.com/hc/en-us/articles/5784100517788-Jobs-Strings). 
  # @param account_id Account ID
  # @param id ID
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_phrase_app_otp Two-Factor-Authentication token (optional)
  # @option opts [Integer] :page Page number
  # @option opts [Integer] :per_page Limit on the number of objects to be returned, between 1 and 100. 25 by default
  # @option opts [String] :state Filter events by outcome state. Unrecognized values are ignored.
  # @option opts [String] :triggered_by Filter events by what triggered the automation run. Unrecognized values are ignored.
  # @option opts [String] :project_id Filter events by project ID. Accepts a single ID or a comma-separated list of IDs.
  # @option opts [Array<String>] :project_ids Filter events by one or more project IDs.
  # @option opts [String] :created_after Return only events created after this ISO 8601 timestamp. Returns 400 if the value is not a valid date-time.
  # @option opts [String] :created_before Return only events created before this ISO 8601 timestamp. Returns 400 if the value is not a valid date-time.
  # @return [Array<AutomationEvent>]
  describe 'automation_events_list test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
