require 'spec_helper'
require 'json'

# Unit tests for Phrase::BitbucketSyncApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'BitbucketSyncApi' do
  before do
    # run before each test
    @api_instance = Phrase::BitbucketSyncApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of BitbucketSyncApi' do
    it 'should create an instance of BitbucketSyncApi' do
      expect(@api_instance).to be_instance_of(Phrase::BitbucketSyncApi)
    end
  end

  # unit tests for bitbucket_sync_export
  # Export from Phrase to Bitbucket
  # Export translations from Phrase to Bitbucket according to the .phraseapp.yml file within the Bitbucket Repository.
  # @param id ID
  # @param bitbucket_sync_export 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_phrase_app_otp Two-Factor-Authentication token (optional)
  # @return [BitbucketSyncExportResponse]
  describe 'bitbucket_sync_export test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for bitbucket_sync_import
  # Import to Phrase from Bitbucket
  # Import translations from Bitbucket to Phrase according to the .phraseapp.yml file within the Bitbucket repository.
  # @param id ID
  # @param bitbucket_sync_import 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_phrase_app_otp Two-Factor-Authentication token (optional)
  # @return [nil]
  describe 'bitbucket_sync_import test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for bitbucket_syncs_list
  # List Bitbucket syncs
  # List all Bitbucket repositories for which synchronisation with Phrase is activated.
  # @param bitbucket_syncs_list 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_phrase_app_otp Two-Factor-Authentication token (optional)
  # @return [Array<BitbucketSync>]
  describe 'bitbucket_syncs_list test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
