require 'spec_helper'
require 'json'

# Unit tests for Phrase::BranchesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'BranchesApi' do
  before do
    # run before each test
    @api_instance = Phrase::BranchesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of BranchesApi' do
    it 'should create an instance of BranchesApi' do
      expect(@api_instance).to be_instance_of(Phrase::BranchesApi)
    end
  end

  # unit tests for branch_compare
  # Compare branches
  # Compare branch with main branch.  *Note: Comparing a branch may take several minutes depending on the project size. Consider using the &#x60;POST /compare&#x60; endpoint for creating comparison asynchronously.* 
  # @param project_id Project ID
  # @param name name
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_phrase_app_otp Two-Factor-Authentication token (optional)
  # @return [nil]
  describe 'branch_compare test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for branch_comparison_create
  # Create comparison (async.)
  # Create a branch comparison asynchronously. 
  # @param project_id Project ID
  # @param name name
  # @param branch_create_comparison_parameters 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_phrase_app_otp Two-Factor-Authentication token (optional)
  # @return [nil]
  describe 'branch_comparison_create test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for branch_create
  # Create a branch
  # Create a new branch.  Branch project provisioning runs asynchronously, so the newly created branch is returned in a transitional state (typically &#x60;creating_branch&#x60;) and only reaches &#x60;success&#x60; once the underlying project has been set up. Poll the branch resource until its &#x60;state&#x60; becomes &#x60;success&#x60; before performing further operations on it.  Requires the Branching feature to be enabled on the account.  *Note: Creating a new branch may take several minutes depending on the project size.* 
  # @param project_id Project ID
  # @param branch_create_parameters 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_phrase_app_otp Two-Factor-Authentication token (optional)
  # @return [Branch]
  describe 'branch_create test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for branch_delete
  # Delete a branch
  # Delete an existing branch.  A branch cannot be deleted while it still has open jobs or open translation orders attached to its branch project — in that case the request is rejected with &#x60;409 Conflict&#x60;. A branch whose current &#x60;state&#x60; does not allow deletion (for example, while a merge or sync is in progress) is rejected with &#x60;422 Unprocessable Entity&#x60;.  Requires the Branching feature to be enabled on the account. 
  # @param project_id Project ID
  # @param name name
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_phrase_app_otp Two-Factor-Authentication token (optional)
  # @return [nil]
  describe 'branch_delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for branch_merge
  # Merge a branch
  # Merge an existing branch back into its base branch.  The merge runs asynchronously. The branch transitions to &#x60;merging_branch&#x60; and settles in &#x60;merged&#x60;, &#x60;merge_error&#x60;, or &#x60;merge_conflict&#x60; once the background job completes; the response body for this request is empty. Poll the branch resource to observe the final state.  A branch cannot be merged while it still has open jobs or open translation orders attached to its branch project — in that case the request is rejected with &#x60;409 Conflict&#x60;. A branch whose current &#x60;state&#x60; does not allow a merge is rejected with &#x60;422 Unprocessable Entity&#x60;.  Requires the Branching feature to be enabled on the account.  *Note: Merging a branch may take several minutes depending on diff size.* 
  # @param project_id Project ID
  # @param name name
  # @param branch_merge_parameters 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_phrase_app_otp Two-Factor-Authentication token (optional)
  # @return [nil]
  describe 'branch_merge test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for branch_show
  # Get a single branch
  # Get details on a single branch for a given project.  Requires the Branching feature to be enabled on the account. 
  # @param project_id Project ID
  # @param name name
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_phrase_app_otp Two-Factor-Authentication token (optional)
  # @return [Branch]
  describe 'branch_show test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for branch_sync
  # Sync a branch
  # Pull changes from the base branch into this branch, applying the chosen conflict-resolution strategy.  The sync runs asynchronously. The branch transitions to &#x60;syncing_branch&#x60; and settles back into &#x60;success&#x60; (or &#x60;merge_conflict&#x60; / &#x60;branch_error&#x60;) once the background job completes; the response body for this request is empty. Poll the branch resource to observe the final state.  Only branches created with the newer branching system can be synced. Requests against branches from the older system, or against branches whose current state does not allow a sync, are rejected with &#x60;422 Unprocessable Entity&#x60; and an empty body.  Requires the Branching feature to be enabled on the account. 
  # @param project_id Project ID
  # @param name name
  # @param branch_sync_parameters 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_phrase_app_otp Two-Factor-Authentication token (optional)
  # @return [nil]
  describe 'branch_sync test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for branch_update
  # Update a branch
  # Update an existing branch. Only the branch name can be changed.  Requires the Branching feature to be enabled on the account. 
  # @param project_id Project ID
  # @param name name
  # @param branch_update_parameters 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_phrase_app_otp Two-Factor-Authentication token (optional)
  # @return [Branch]
  describe 'branch_update test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for branches_list
  # List branches
  # List all branches of the current project.  Requires the Branching feature to be enabled on the account. 
  # @param project_id Project ID
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_phrase_app_otp Two-Factor-Authentication token (optional)
  # @option opts [Integer] :page Page number
  # @option opts [Integer] :per_page Limit on the number of objects to be returned, between 1 and 100. 25 by default
  # @return [Array<Branch>]
  describe 'branches_list test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
