require 'spec_helper'
require 'json'

# Unit tests for Phrase::ChecksApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ChecksApi' do
  before do
    # run before each test
    @api_instance = Phrase::ChecksApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ChecksApi' do
    it 'should create an instance of ChecksApi' do
      expect(@api_instance).to be_instance_of(Phrase::ChecksApi)
    end
  end

  # unit tests for check_issue_dismiss
  # Dismiss a check issue
  # **Note:** The Checks API is still in development and might change in subsequent releases.  Mark a check issue as dismissed so it no longer appears on the list of active check issues.
  # @param project_id Project ID
  # @param id Check Issue ID
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_phrase_app_otp Two-Factor-Authentication token (optional)
  # @return [CheckIssue]
  describe 'check_issue_dismiss test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for check_issues_list
  # List check issues
  # **Note:** The Checks API is still in development and might change in subsequent releases.  List check issues for the given project. Results can be filtered by locale, check name, and state.
  # @param project_id Project ID
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_phrase_app_otp Two-Factor-Authentication token (optional)
  # @option opts [Integer] :page Page number
  # @option opts [Integer] :per_page Limit on the number of objects to be returned, between 1 and 100. 25 by default
  # @option opts [String] :state Filter by state of the check issue. Can be one of: &#x60;active&#x60;, &#x60;solved&#x60;, &#x60;dismissed&#x60;, &#x60;all&#x60;. Defaults to &#x60;active&#x60;.
  # @option opts [Array<String>] :locale_ids Filter by one or more locale IDs.
  # @option opts [Array<String>] :check_names Filter by one or more check names. Valid values are:  - &#x60;translation_content_length&#x60; — the translation exceeds the maximum character limit configured for the key. - &#x60;translation_placeholder_usage&#x60; — the translation is missing placeholders present in the source, or contains unexpected ones. - &#x60;translation_glossary_usage&#x60; — the translation does not follow the glossary term translations.
  # @return [Array<CheckIssue>]
  describe 'check_issues_list test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
