require 'spec_helper'
require 'json'

# Unit tests for Phrase::FormatsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'FormatsApi' do
  before do
    # run before each test
    @api_instance = Phrase::FormatsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of FormatsApi' do
    it 'should create an instance of FormatsApi' do
      expect(@api_instance).to be_instance_of(Phrase::FormatsApi)
    end
  end

  # unit tests for formats_list
  # List formats
  # Get a handy list of all localization file formats supported in Phrase.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_phrase_app_otp Two-Factor-Authentication token (optional)
  # @return [Array<Format>]
  describe 'formats_list test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
