require 'spec_helper'
require 'json'

# Unit tests for Phrase::ICUApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ICUApi' do
  before do
    # run before each test
    @api_instance = Phrase::ICUApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ICUApi' do
    it 'should create an instance of ICUApi' do
      expect(@api_instance).to be_instance_of(Phrase::ICUApi)
    end
  end

  # unit tests for icu_skeleton
  # Build ICU skeletons
  # Generates ICU (International Components for Unicode) message format skeletons for a given source string across one or more locales. An ICU skeleton strips the literal text from a pluralized or select message while preserving its structural rules — argument names, plural categories, select cases, and ordinal forms — adjusted to the pluralization rules of each requested locale.  Use this endpoint to normalize translation templates before importing them into locale files, or to validate that a source string carries the plural forms required by a target language.  Either &#x60;content&#x60; or &#x60;id&#x60; must be provided — supplying both or neither returns 400. When &#x60;id&#x60; is used and the referenced translation does not exist, the endpoint returns 404. When the source string is not valid ICU message format syntax, the endpoint returns 422 with an &#x60;error&#x60; field describing the parse failure. 
  # @param icu_skeleton_parameters 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_phrase_app_otp Two-Factor-Authentication token (optional)
  # @return [Icu]
  describe 'icu_skeleton test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
