require 'spec_helper'
require 'json'

# Unit tests for Phrase::ICUApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ICUApi' do
  before do
    # run before each test
    @api_instance = Phrase::ICUApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ICUApi' do
    it 'should create an instance of ICUApi' do
      expect(@api_instance).to be_instance_of(Phrase::ICUApi)
    end
  end

  # unit tests for icu_skeleton
  # Build ICU skeletons
  # Returns ICU skeletons for multiple locale codes based on a source content.
  # @param icu_skeleton_parameters 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_phrase_app_otp Two-Factor-Authentication token (optional)
  # @return [Icu]
  describe 'icu_skeleton test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
