require 'spec_helper'
require 'json'

# Unit tests for Phrase::KeyFormatAnnotationsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'KeyFormatAnnotationsApi' do
  before do
    # run before each test
    @api_instance = Phrase::KeyFormatAnnotationsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of KeyFormatAnnotationsApi' do
    it 'should create an instance of KeyFormatAnnotationsApi' do
      expect(@api_instance).to be_instance_of(Phrase::KeyFormatAnnotationsApi)
    end
  end

  # unit tests for key_format_annotations_list
  # List format annotations for a key
  # Returns the format annotations stored on a translation key. Format annotations capture file-format data recorded when the key was imported — for example, an ARB placeholder block or an XLIFF note.  Results are limited to 1,000 entries. 
  # @param project_id Project ID
  # @param id ID
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_phrase_app_otp Two-Factor-Authentication token (optional)
  # @option opts [String] :branch Branch to use
  # @return [Array<KeyFormatAnnotationsList200ResponseInner>]
  describe 'key_format_annotations_list test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
