require 'spec_helper'
require 'json'

# Unit tests for Phrase::KeysFigmaAttachmentsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'KeysFigmaAttachmentsApi' do
  before do
    # run before each test
    @api_instance = Phrase::KeysFigmaAttachmentsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of KeysFigmaAttachmentsApi' do
    it 'should create an instance of KeysFigmaAttachmentsApi' do
      expect(@api_instance).to be_instance_of(Phrase::KeysFigmaAttachmentsApi)
    end
  end

  # unit tests for figma_attachment_attach_to_key
  # Attach the Figma attachment to a key
  # Attach the Figma attachment to a key
  # @param project_id Project ID
  # @param figma_attachment_id Figma attachment ID
  # @param id ID
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_phrase_app_otp Two-Factor-Authentication token (optional)
  # @option opts [String] :branch specify the branch to use
  # @return [nil]
  describe 'figma_attachment_attach_to_key test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for figma_attachment_detach_from_key
  # Detach the Figma attachment from a key
  # Detach the Figma attachment from a key
  # @param project_id Project ID
  # @param figma_attachment_id Figma attachment ID
  # @param id ID
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_phrase_app_otp Two-Factor-Authentication token (optional)
  # @option opts [String] :branch specify the branch to use
  # @return [nil]
  describe 'figma_attachment_detach_from_key test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
