require 'spec_helper'
require 'json'

# Unit tests for Phrase::LinkedKeysApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'LinkedKeysApi' do
  before do
    # run before each test
    @api_instance = Phrase::LinkedKeysApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of LinkedKeysApi' do
    it 'should create an instance of LinkedKeysApi' do
      expect(@api_instance).to be_instance_of(Phrase::LinkedKeysApi)
    end
  end

  # unit tests for key_links_batch_destroy
  # Batch unlink child keys from a parent key
  # Unlinks multiple child keys from a given parent key in a single operation.
  # @param project_id Project ID
  # @param id Parent Translation Key ID
  # @param key_links_batch_destroy_parameters 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_phrase_app_otp Two-Factor-Authentication token (optional)
  # @return [nil]
  describe 'key_links_batch_destroy test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for key_links_create
  # Link child keys to a parent key
  # Creates links between a given parent key and one or more child keys.
  # @param project_id Project ID
  # @param id Parent Translation Key ID
  # @param key_links_create_parameters 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_phrase_app_otp Two-Factor-Authentication token (optional)
  # @return [KeyLink]
  describe 'key_links_create test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for key_links_destroy
  # Unlink a child key from a parent key
  # Unlinks a single child key from a given parent key.
  # @param project_id Project ID
  # @param id Parent Translation Key ID
  # @param child_key_id The ID of the child key to unlink.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_phrase_app_otp Two-Factor-Authentication token (optional)
  # @return [nil]
  describe 'key_links_destroy test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for key_links_index
  # List child keys of a parent key
  # Returns detailed information about a parent key, including its linked child keys.
  # @param project_id Project ID
  # @param id Parent Translation Key ID
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_phrase_app_otp Two-Factor-Authentication token (optional)
  # @return [KeyLink]
  describe 'key_links_index test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
