require 'spec_helper'
require 'json'

# Unit tests for Phrase::NotificationGroupsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'NotificationGroupsApi' do
  before do
    # run before each test
    @api_instance = Phrase::NotificationGroupsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of NotificationGroupsApi' do
    it 'should create an instance of NotificationGroupsApi' do
      expect(@api_instance).to be_instance_of(Phrase::NotificationGroupsApi)
    end
  end

  # unit tests for notification_groups_list
  # List notification groups
  # List all notification groups from the current user
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_phrase_app_otp Two-Factor-Authentication token (optional)
  # @option opts [Integer] :page Page number
  # @option opts [Integer] :per_page Limit on the number of objects to be returned, between 1 and 100. 25 by default
  # @return [Array<Object>]
  describe 'notification_groups_list test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for notification_groups_mark_all_as_read
  # Mark all notification groups as read
  # Mark all notification groups of the current user as read
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_phrase_app_otp Two-Factor-Authentication token (optional)
  # @return [Array<Object>]
  describe 'notification_groups_mark_all_as_read test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for notification_groups_mark_as_read
  # Mark a notification group as read
  # Mark a notifications group of the current user as read
  # @param id ID
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_phrase_app_otp Two-Factor-Authentication token (optional)
  # @return [NotificationGroupDetail]
  describe 'notification_groups_mark_as_read test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
