require 'spec_helper'
require 'json'

# Unit tests for Phrase::OrganizationJobTemplateLocalesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'OrganizationJobTemplateLocalesApi' do
  before do
    # run before each test
    @api_instance = Phrase::OrganizationJobTemplateLocalesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of OrganizationJobTemplateLocalesApi' do
    it 'should create an instance of OrganizationJobTemplateLocalesApi' do
      expect(@api_instance).to be_instance_of(Phrase::OrganizationJobTemplateLocalesApi)
    end
  end

  # unit tests for organization_job_template_locale_delete
  # Delete an organization job template locale
  # Delete an existing organization job template locale.
  # @param account_id Account ID
  # @param job_template_id Job Template ID
  # @param job_template_locale_id Job Template Locale ID
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_phrase_app_otp Two-Factor-Authentication token (optional)
  # @return [nil]
  describe 'organization_job_template_locale_delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for organization_job_template_locale_show
  # Get a single organization job template locale
  # Get a single job template locale for a given organization job template.
  # @param account_id Account ID
  # @param job_template_id Job Template ID
  # @param job_template_locale_id Job Template Locale ID
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_phrase_app_otp Two-Factor-Authentication token (optional)
  # @return [JobTemplateLocales]
  describe 'organization_job_template_locale_show test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for organization_job_template_locale_update
  # Update an organization job template locale
  # Update an existing organization job template locale.
  # @param account_id Account ID
  # @param job_template_id Job Template ID
  # @param job_template_locale_id Job Template Locale ID
  # @param organization_job_template_locale_update_parameters 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_phrase_app_otp Two-Factor-Authentication token (optional)
  # @return [JobTemplateLocales]
  describe 'organization_job_template_locale_update test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for organization_job_template_locales_create
  # Create an organization job template locale
  # Create a new organization job template locale.
  # @param account_id Account ID
  # @param job_template_id Job Template ID
  # @param organization_job_template_locales_create_parameters 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_phrase_app_otp Two-Factor-Authentication token (optional)
  # @return [JobTemplateLocales]
  describe 'organization_job_template_locales_create test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for organization_job_template_locales_list
  # List organization job template locales
  # List all job template locales for a given organization job template.
  # @param account_id Account ID
  # @param job_template_id Job Template ID
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_phrase_app_otp Two-Factor-Authentication token (optional)
  # @option opts [Integer] :page Page number
  # @option opts [Integer] :per_page Limit on the number of objects to be returned, between 1 and 100. 25 by default
  # @return [Array<JobTemplateLocales>]
  describe 'organization_job_template_locales_list test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
