require 'spec_helper'
require 'json'

# Unit tests for Phrase::SupportedLanguagesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'SupportedLanguagesApi' do
  before do
    # run before each test
    @api_instance = Phrase::SupportedLanguagesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SupportedLanguagesApi' do
    it 'should create an instance of SupportedLanguagesApi' do
      expect(@api_instance).to be_instance_of(Phrase::SupportedLanguagesApi)
    end
  end

  # unit tests for languages_list
  # List supported languages
  # Returns all languages/locale codes that Phrase Strings recognizes, mapped to their human-readable display name. This endpoint does not require authentication. 
  # @param [Hash] opts the optional parameters
  # @return [Hash<String, String>]
  describe 'languages_list test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
