require 'spec_helper'
require 'json'

# Unit tests for Phrase::TermBaseTranslationApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'TermBaseTranslationApi' do
  before do
    # run before each test
    @api_instance = Phrase::TermBaseTranslationApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of TermBaseTranslationApi' do
    it 'should create an instance of TermBaseTranslationApi' do
      expect(@api_instance).to be_instance_of(Phrase::TermBaseTranslationApi)
    end
  end

  # unit tests for glossary_term_translation_delete
  # Delete a translation for a term
  # Delete an existing translation of a term in a term base (previously: glossary).
  # @param account_id Account ID
  # @param glossary_id Glossary ID
  # @param term_id Term ID
  # @param id ID
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_phrase_app_otp Two-Factor-Authentication token (optional)
  # @return [nil]
  describe 'glossary_term_translation_delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
