require 'spec_helper'
require 'json'

# Unit tests for Phrase::VersionsHistoryApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'VersionsHistoryApi' do
  before do
    # run before each test
    @api_instance = Phrase::VersionsHistoryApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of VersionsHistoryApi' do
    it 'should create an instance of VersionsHistoryApi' do
      expect(@api_instance).to be_instance_of(Phrase::VersionsHistoryApi)
    end
  end

  # unit tests for version_show
  # Get a single version
  # Get details on a single version.
  # @param project_id Project ID
  # @param translation_id Translation ID
  # @param id ID
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_phrase_app_otp Two-Factor-Authentication token (optional)
  # @option opts [String] :branch specify the branch to use
  # @return [TranslationVersionWithUser]
  describe 'version_show test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for versions_list
  # List all versions
  # List all changes done to a given translation.
  # @param project_id Project ID
  # @param translation_id Translation ID
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_phrase_app_otp Two-Factor-Authentication token (optional)
  # @option opts [Integer] :page Page number
  # @option opts [Integer] :per_page allows you to specify a page size up to 100 items, 25 by default
  # @option opts [String] :branch specify the branch to use
  # @return [Array<TranslationVersion>]
  describe 'versions_list test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
