require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Phrase::AffectedResources
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'AffectedResources' do
  before do
    # run before each test
    @instance = Phrase::AffectedResources.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AffectedResources' do
    it 'should create an instance of AffectedResources' do
      expect(@instance).to be_instance_of(Phrase::AffectedResources)
    end
  end
  describe 'test attribute "records_affected"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
