require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Phrase::AuthorizationCreateParameters
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'AuthorizationCreateParameters' do
  before do
    # run before each test
    @instance = Phrase::AuthorizationCreateParameters.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AuthorizationCreateParameters' do
    it 'should create an instance of AuthorizationCreateParameters' do
      expect(@instance).to be_instance_of(Phrase::AuthorizationCreateParameters)
    end
  end
  describe 'test attribute "note"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "scopes"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "expires_at"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
