require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Phrase::BitbucketSyncExportResponse
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'BitbucketSyncExportResponse' do
  before do
    # run before each test
    @instance = Phrase::BitbucketSyncExportResponse.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of BitbucketSyncExportResponse' do
    it 'should create an instance of BitbucketSyncExportResponse' do
      expect(@instance).to be_instance_of(Phrase::BitbucketSyncExportResponse)
    end
  end
  describe 'test attribute "status_path"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
