require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Phrase::BitbucketSyncsList
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'BitbucketSyncsList' do
  before do
    # run before each test
    @instance = Phrase::BitbucketSyncsList.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of BitbucketSyncsList' do
    it 'should create an instance of BitbucketSyncsList' do
      expect(@instance).to be_instance_of(Phrase::BitbucketSyncsList)
    end
  end
  describe 'test attribute "account_id"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
