require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Phrase::BranchComparisonDiffConflictsValue
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'BranchComparisonDiffConflictsValue' do
  before do
    # run before each test
    @instance = Phrase::BranchComparisonDiffConflictsValue.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of BranchComparisonDiffConflictsValue' do
    it 'should create an instance of BranchComparisonDiffConflictsValue' do
      expect(@instance).to be_instance_of(Phrase::BranchComparisonDiffConflictsValue)
    end
  end
  describe 'test attribute "base"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "head"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
