require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Phrase::BranchCompare
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'BranchCompare' do
  before do
    # run before each test
    @instance = Phrase::BranchCompare.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of BranchCompare' do
    it 'should create an instance of BranchCompare' do
      expect(@instance).to be_instance_of(Phrase::BranchCompare)
    end
  end
  describe 'test attribute "name"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
