require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Phrase::BranchComparisonDiff
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'BranchComparisonDiff' do
  before do
    # run before each test
    @instance = Phrase::BranchComparisonDiff.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of BranchComparisonDiff' do
    it 'should create an instance of BranchComparisonDiff' do
      expect(@instance).to be_instance_of(Phrase::BranchComparisonDiff)
    end
  end
  describe 'test attribute "base_changes"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "head_changes"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "conflicts"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
