require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Phrase::BranchComparisonChange
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'BranchComparisonChange' do
  before do
    # run before each test
    @instance = Phrase::BranchComparisonChange.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of BranchComparisonChange' do
    it 'should create an instance of BranchComparisonChange' do
      expect(@instance).to be_instance_of(Phrase::BranchComparisonChange)
    end
  end
  describe 'test attribute "from"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "to"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
