require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Phrase::CommentCreate
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'CommentCreate' do
  before do
    # run before each test
    @instance = Phrase::CommentCreate.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CommentCreate' do
    it 'should create an instance of CommentCreate' do
      expect(@instance).to be_instance_of(Phrase::CommentCreate)
    end
  end
  describe 'test attribute "branch"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "message"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
