require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Phrase::CommentsListParameters
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'CommentsListParameters' do
  before do
    # run before each test
    @instance = Phrase::CommentsListParameters.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CommentsListParameters' do
    it 'should create an instance of CommentsListParameters' do
      expect(@instance).to be_instance_of(Phrase::CommentsListParameters)
    end
  end
  describe 'test attribute "branch"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "query"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "locale_ids"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "filters"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
