require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Phrase::CustomMetadataPropertiesCreateParameters
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'CustomMetadataPropertiesCreateParameters' do
  before do
    # run before each test
    @instance = Phrase::CustomMetadataPropertiesCreateParameters.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CustomMetadataPropertiesCreateParameters' do
    it 'should create an instance of CustomMetadataPropertiesCreateParameters' do
      expect(@instance).to be_instance_of(Phrase::CustomMetadataPropertiesCreateParameters)
    end
  end
  describe 'test attribute "name"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "data_type"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "project_ids"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "description"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "value_options"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
