require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Phrase::CustomMetadataDataType
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'CustomMetadataDataType' do
  before do
    # run before each test
    @instance = Phrase::CustomMetadataDataType.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CustomMetadataDataType' do
    it 'should create an instance of CustomMetadataDataType' do
      expect(@instance).to be_instance_of(Phrase::CustomMetadataDataType)
    end
  end
end
