require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Phrase::DocumentDelete422Response
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'DocumentDelete422Response' do
  before do
    # run before each test
    @instance = Phrase::DocumentDelete422Response.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DocumentDelete422Response' do
    it 'should create an instance of DocumentDelete422Response' do
      expect(@instance).to be_instance_of(Phrase::DocumentDelete422Response)
    end
  end
  describe 'test attribute "message"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "errors"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
