require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Phrase::ErrorError
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ErrorError' do
  before do
    # run before each test
    @instance = Phrase::ErrorError.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ErrorError' do
    it 'should create an instance of ErrorError' do
      expect(@instance).to be_instance_of(Phrase::ErrorError)
    end
  end
  describe 'test attribute "message"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "code"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
