require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Phrase::GitlabSyncUpdateParameters
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'GitlabSyncUpdateParameters' do
  before do
    # run before each test
    @instance = Phrase::GitlabSyncUpdateParameters.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of GitlabSyncUpdateParameters' do
    it 'should create an instance of GitlabSyncUpdateParameters' do
      expect(@instance).to be_instance_of(Phrase::GitlabSyncUpdateParameters)
    end
  end
  describe 'test attribute "account_id"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "phrase_project_code"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "gitlab_project_id"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "gitlab_branch_name"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
