require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Phrase::GitlabSyncHistory
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'GitlabSyncHistory' do
  before do
    # run before each test
    @instance = Phrase::GitlabSyncHistory.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of GitlabSyncHistory' do
    it 'should create an instance of GitlabSyncHistory' do
      expect(@instance).to be_instance_of(Phrase::GitlabSyncHistory)
    end
  end
  describe 'test attribute "status"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "action"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "errors"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "date"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "details"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
