require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Phrase::GlossaryTermGlossary
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'GlossaryTermGlossary' do
  before do
    # run before each test
    @instance = Phrase::GlossaryTermGlossary.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of GlossaryTermGlossary' do
    it 'should create an instance of GlossaryTermGlossary' do
      expect(@instance).to be_instance_of(Phrase::GlossaryTermGlossary)
    end
  end
  describe 'test attribute "id"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "name"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
