require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Phrase::GlossaryTermTranslationCreate
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'GlossaryTermTranslationCreate' do
  before do
    # run before each test
    @instance = Phrase::GlossaryTermTranslationCreate.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of GlossaryTermTranslationCreate' do
    it 'should create an instance of GlossaryTermTranslationCreate' do
      expect(@instance).to be_instance_of(Phrase::GlossaryTermTranslationCreate)
    end
  end
  describe 'test attribute "locale_code"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "content"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
