require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Phrase::GlossaryUpdate
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'GlossaryUpdate' do
  before do
    # run before each test
    @instance = Phrase::GlossaryUpdate.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of GlossaryUpdate' do
    it 'should create an instance of GlossaryUpdate' do
      expect(@instance).to be_instance_of(Phrase::GlossaryUpdate)
    end
  end
  describe 'test attribute "name"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "project_ids"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "space_ids"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
