require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Phrase::GlossaryCreateParameters
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'GlossaryCreateParameters' do
  before do
    # run before each test
    @instance = Phrase::GlossaryCreateParameters.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of GlossaryCreateParameters' do
    it 'should create an instance of GlossaryCreateParameters' do
      expect(@instance).to be_instance_of(Phrase::GlossaryCreateParameters)
    end
  end
  describe 'test attribute "name"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "project_ids"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "space_ids"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
