require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Phrase::GlossaryTermCreateParameters
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'GlossaryTermCreateParameters' do
  before do
    # run before each test
    @instance = Phrase::GlossaryTermCreateParameters.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of GlossaryTermCreateParameters' do
    it 'should create an instance of GlossaryTermCreateParameters' do
      expect(@instance).to be_instance_of(Phrase::GlossaryTermCreateParameters)
    end
  end
  describe 'test attribute "term"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "description"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "translatable"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "case_sensitive"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
