require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Phrase::IcuSkeletonParameters
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'IcuSkeletonParameters' do
  before do
    # run before each test
    @instance = Phrase::IcuSkeletonParameters.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of IcuSkeletonParameters' do
    it 'should create an instance of IcuSkeletonParameters' do
      expect(@instance).to be_instance_of(Phrase::IcuSkeletonParameters)
    end
  end
  describe 'test attribute "content"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "locale_codes"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "zero_form_enabled"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
