require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Phrase::InlineResponse422Errors
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'InlineResponse422Errors' do
  before do
    # run before each test
    @instance = Phrase::InlineResponse422Errors.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of InlineResponse422Errors' do
    it 'should create an instance of InlineResponse422Errors' do
      expect(@instance).to be_instance_of(Phrase::InlineResponse422Errors)
    end
  end
  describe 'test attribute "resource"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "field"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "message"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
