require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Phrase::InvitationUpdateSettingsParameters
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'InvitationUpdateSettingsParameters' do
  before do
    # run before each test
    @instance = Phrase::InvitationUpdateSettingsParameters.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of InvitationUpdateSettingsParameters' do
    it 'should create an instance of InvitationUpdateSettingsParameters' do
      expect(@instance).to be_instance_of(Phrase::InvitationUpdateSettingsParameters)
    end
  end
  describe 'test attribute "project_role"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "locale_ids"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
