require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Phrase::JobReopenParameters
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'JobReopenParameters' do
  before do
    # run before each test
    @instance = Phrase::JobReopenParameters.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of JobReopenParameters' do
    it 'should create an instance of JobReopenParameters' do
      expect(@instance).to be_instance_of(Phrase::JobReopenParameters)
    end
  end
  describe 'test attribute "branch"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
