require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Phrase::JobTemplateLocale
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'JobTemplateLocale' do
  before do
    # run before each test
    @instance = Phrase::JobTemplateLocale.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of JobTemplateLocale' do
    it 'should create an instance of JobTemplateLocale' do
      expect(@instance).to be_instance_of(Phrase::JobTemplateLocale)
    end
  end
  describe 'test attribute "id"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "job_template"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "locale"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "users"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
