require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Phrase::JobTemplateCreateParameters
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'JobTemplateCreateParameters' do
  before do
    # run before each test
    @instance = Phrase::JobTemplateCreateParameters.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of JobTemplateCreateParameters' do
    it 'should create an instance of JobTemplateCreateParameters' do
      expect(@instance).to be_instance_of(Phrase::JobTemplateCreateParameters)
    end
  end
  describe 'test attribute "branch"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "name"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "briefing"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
