require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Phrase::JobTemplateDetails1
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'JobTemplateDetails1' do
  before do
    # run before each test
    @instance = Phrase::JobTemplateDetails1.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of JobTemplateDetails1' do
    it 'should create an instance of JobTemplateDetails1' do
      expect(@instance).to be_instance_of(Phrase::JobTemplateDetails1)
    end
  end
  describe 'test attribute "owner"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "creator"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "locales"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
