require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Phrase::KeyLinksBatchDestroyParameters
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'KeyLinksBatchDestroyParameters' do
  before do
    # run before each test
    @instance = Phrase::KeyLinksBatchDestroyParameters.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of KeyLinksBatchDestroyParameters' do
    it 'should create an instance of KeyLinksBatchDestroyParameters' do
      expect(@instance).to be_instance_of(Phrase::KeyLinksBatchDestroyParameters)
    end
  end
  describe 'test attribute "child_key_ids"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "unlink_parent"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "strategy"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["keep_content", "remove_content"])
      # validator.allowable_values.each do |value|
      #   expect { @instance.strategy = value }.not_to raise_error
      # end
    end
  end

end
