require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Phrase::KeyPreview
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'KeyPreview' do
  before do
    # run before each test
    @instance = Phrase::KeyPreview.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of KeyPreview' do
    it 'should create an instance of KeyPreview' do
      expect(@instance).to be_instance_of(Phrase::KeyPreview)
    end
  end
  describe 'test attribute "id"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "name"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "plural"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
