require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Phrase::KeyFormatAnnotationsList200ResponseInner
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'KeyFormatAnnotationsList200ResponseInner' do
  before do
    # run before each test
    @instance = Phrase::KeyFormatAnnotationsList200ResponseInner.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of KeyFormatAnnotationsList200ResponseInner' do
    it 'should create an instance of KeyFormatAnnotationsList200ResponseInner' do
      expect(@instance).to be_instance_of(Phrase::KeyFormatAnnotationsList200ResponseInner)
    end
  end
  describe 'test attribute "file_format"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "original_representation"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
