require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Phrase::MachineTranslationSettings
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'MachineTranslationSettings' do
  before do
    # run before each test
    @instance = Phrase::MachineTranslationSettings.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of MachineTranslationSettings' do
    it 'should create an instance of MachineTranslationSettings' do
      expect(@instance).to be_instance_of(Phrase::MachineTranslationSettings)
    end
  end
  describe 'test attribute "default_service"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "machine_translation_units_used"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "machine_translation_units_total"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "locale_provider_mappings"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
