require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Phrase::MemberUpdateSettingsParameters
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'MemberUpdateSettingsParameters' do
  before do
    # run before each test
    @instance = Phrase::MemberUpdateSettingsParameters.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of MemberUpdateSettingsParameters' do
    it 'should create an instance of MemberUpdateSettingsParameters' do
      expect(@instance).to be_instance_of(Phrase::MemberUpdateSettingsParameters)
    end
  end
  describe 'test attribute "project_role"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "locale_ids"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
