require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Phrase::MemberProjectDetailProjectRolesInner
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'MemberProjectDetailProjectRolesInner' do
  before do
    # run before each test
    @instance = Phrase::MemberProjectDetailProjectRolesInner.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of MemberProjectDetailProjectRolesInner' do
    it 'should create an instance of MemberProjectDetailProjectRolesInner' do
      expect(@instance).to be_instance_of(Phrase::MemberProjectDetailProjectRolesInner)
    end
  end
  describe 'test attribute "project_id"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "role"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
