require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Phrase::OrganizationJobTemplateLocalesCreateParameters
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'OrganizationJobTemplateLocalesCreateParameters' do
  before do
    # run before each test
    @instance = Phrase::OrganizationJobTemplateLocalesCreateParameters.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of OrganizationJobTemplateLocalesCreateParameters' do
    it 'should create an instance of OrganizationJobTemplateLocalesCreateParameters' do
      expect(@instance).to be_instance_of(Phrase::OrganizationJobTemplateLocalesCreateParameters)
    end
  end
  describe 'test attribute "locale_name"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "locale_code"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "user_ids"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "reviewer_ids"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "translator_team_ids"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "reviewer_team_ids"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
