require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Phrase::ProjectDetails1
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ProjectDetails1' do
  before do
    # run before each test
    @instance = Phrase::ProjectDetails1.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ProjectDetails1' do
    it 'should create an instance of ProjectDetails1' do
      expect(@instance).to be_instance_of(Phrase::ProjectDetails1)
    end
  end
  describe 'test attribute "slug"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "shares_translation_memory"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
