require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Phrase::ProjectLocales1
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ProjectLocales1' do
  before do
    # run before each test
    @instance = Phrase::ProjectLocales1.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ProjectLocales1' do
    it 'should create an instance of ProjectLocales1' do
      expect(@instance).to be_instance_of(Phrase::ProjectLocales1)
    end
  end
  describe 'test attribute "locales"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
