require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Phrase::ProjectsQualityPerformanceScore200ResponseAnyOfDataTranslationsInner
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ProjectsQualityPerformanceScore200ResponseAnyOfDataTranslationsInner' do
  before do
    # run before each test
    @instance = Phrase::ProjectsQualityPerformanceScore200ResponseAnyOfDataTranslationsInner.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ProjectsQualityPerformanceScore200ResponseAnyOfDataTranslationsInner' do
    it 'should create an instance of ProjectsQualityPerformanceScore200ResponseAnyOfDataTranslationsInner' do
      expect(@instance).to be_instance_of(Phrase::ProjectsQualityPerformanceScore200ResponseAnyOfDataTranslationsInner)
    end
  end
  describe 'test attribute "engine"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "score"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "id"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
