require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Phrase::QualityPerformanceScoreList200ResponseAnyOf
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'QualityPerformanceScoreList200ResponseAnyOf' do
  before do
    # run before each test
    @instance = Phrase::QualityPerformanceScoreList200ResponseAnyOf.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of QualityPerformanceScoreList200ResponseAnyOf' do
    it 'should create an instance of QualityPerformanceScoreList200ResponseAnyOf' do
      expect(@instance).to be_instance_of(Phrase::QualityPerformanceScoreList200ResponseAnyOf)
    end
  end
  describe 'test attribute "data"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "errors"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
