require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Phrase::ReleaseUpdateParameters
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ReleaseUpdateParameters' do
  before do
    # run before each test
    @instance = Phrase::ReleaseUpdateParameters.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ReleaseUpdateParameters' do
    it 'should create an instance of ReleaseUpdateParameters' do
      expect(@instance).to be_instance_of(Phrase::ReleaseUpdateParameters)
    end
  end
  describe 'test attribute "description"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "platforms"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "branch"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
