require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Phrase::ReleaseUpdate
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ReleaseUpdate' do
  before do
    # run before each test
    @instance = Phrase::ReleaseUpdate.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ReleaseUpdate' do
    it 'should create an instance of ReleaseUpdate' do
      expect(@instance).to be_instance_of(Phrase::ReleaseUpdate)
    end
  end
  describe 'test attribute "description"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "platforms"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "branch"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
