require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Phrase::RepoSyncCreateParameters
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'RepoSyncCreateParameters' do
  before do
    # run before each test
    @instance = Phrase::RepoSyncCreateParameters.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of RepoSyncCreateParameters' do
    it 'should create an instance of RepoSyncCreateParameters' do
      expect(@instance).to be_instance_of(Phrase::RepoSyncCreateParameters)
    end
  end
  describe 'test attribute "project_id"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "name"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "git_provider"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["github", "gitlab", "bitbucket"])
      # validator.allowable_values.each do |value|
      #   expect { @instance.git_provider = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "connection_type"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["token", "github_app", "self_hosted"])
      # validator.allowable_values.each do |value|
      #   expect { @instance.connection_type = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "repo_name"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "base_branch"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "pr_branch"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "auto_import"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "access_token"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "custom_api_endpoint"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
