require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Phrase::ScreenshotMarkerCreate
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ScreenshotMarkerCreate' do
  before do
    # run before each test
    @instance = Phrase::ScreenshotMarkerCreate.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ScreenshotMarkerCreate' do
    it 'should create an instance of ScreenshotMarkerCreate' do
      expect(@instance).to be_instance_of(Phrase::ScreenshotMarkerCreate)
    end
  end
  describe 'test attribute "key_id"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "presentation"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
