require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Phrase::SearchInAccountParameters
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'SearchInAccountParameters' do
  before do
    # run before each test
    @instance = Phrase::SearchInAccountParameters.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SearchInAccountParameters' do
    it 'should create an instance of SearchInAccountParameters' do
      expect(@instance).to be_instance_of(Phrase::SearchInAccountParameters)
    end
  end
  describe 'test attribute "query"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "locale_code"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "page"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "per_page"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
