require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Phrase::SpacesProjectsCreateParameters
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'SpacesProjectsCreateParameters' do
  before do
    # run before each test
    @instance = Phrase::SpacesProjectsCreateParameters.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SpacesProjectsCreateParameters' do
    it 'should create an instance of SpacesProjectsCreateParameters' do
      expect(@instance).to be_instance_of(Phrase::SpacesProjectsCreateParameters)
    end
  end
  describe 'test attribute "id"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
