require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Phrase::Styleguide
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'Styleguide' do
  before do
    # run before each test
    @instance = Phrase::Styleguide.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of Styleguide' do
    it 'should create an instance of Styleguide' do
      expect(@instance).to be_instance_of(Phrase::Styleguide)
    end
  end
  describe 'test attribute "id"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "title"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "created_at"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "updated_at"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
