require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Phrase::TagShowParameters
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'TagShowParameters' do
  before do
    # run before each test
    @instance = Phrase::TagShowParameters.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of TagShowParameters' do
    it 'should create an instance of TagShowParameters' do
      expect(@instance).to be_instance_of(Phrase::TagShowParameters)
    end
  end
  describe 'test attribute "branch"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
