require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Phrase::TranslationParent
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'TranslationParent' do
  before do
    # run before each test
    @instance = Phrase::TranslationParent.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of TranslationParent' do
    it 'should create an instance of TranslationParent' do
      expect(@instance).to be_instance_of(Phrase::TranslationParent)
    end
  end
  describe 'test attribute "id"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "content"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
