require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Phrase::TranslationDetails1
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'TranslationDetails1' do
  before do
    # run before each test
    @instance = Phrase::TranslationDetails1.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of TranslationDetails1' do
    it 'should create an instance of TranslationDetails1' do
      expect(@instance).to be_instance_of(Phrase::TranslationDetails1)
    end
  end
  describe 'test attribute "user"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "word_count"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
