require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Phrase::TranslationsList
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'TranslationsList' do
  before do
    # run before each test
    @instance = Phrase::TranslationsList.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of TranslationsList' do
    it 'should create an instance of TranslationsList' do
      expect(@instance).to be_instance_of(Phrase::TranslationsList)
    end
  end
  describe 'test attribute "branch"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "sort"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "order"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "q"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
