require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Phrase::WebhookCreate
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'WebhookCreate' do
  before do
    # run before each test
    @instance = Phrase::WebhookCreate.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of WebhookCreate' do
    it 'should create an instance of WebhookCreate' do
      expect(@instance).to be_instance_of(Phrase::WebhookCreate)
    end
  end
  describe 'test attribute "callback_url"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "description"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "events"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "active"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
